### ISSUE TITLE
Implement scanning without registry creds

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-security-hub#135]
The UDS packages contain all the container images within the tarball. Currently, the code uses `sbom` and the `index.json` to retrieve container names and pull the containers from the registry for scanning.

In a disconnected environment, access to remote registries won't be available.

We need to implement logic to enable offline scanning by inspecting the tarball.

```[tasklist]
### Tasks
- [x] Implement for local scanning
- [ ] Implement for remote scanning.
- [x] Fix the `e2e` test.
- [x] Update the docs.
- [x] Update the GH actions to reflect these changes.
```

We also need to ensure that the code still maps each layer to the corresponding container image to ensure that CVE information maps to those containers.
