### ISSUE TITLE
Implement full image scanning for both local and remote

### ISSUE THREAD

**Issue by partkyle** [defenseunicorns/uds-security-hub#149]
#135 introduced local scanning using the SBOM from the `sboms.tar` file inside the zarf package.

The sbom scanner returns less information than the remote scanner. We should use the `trivy rootfs` scanner for local scanning. Then we can modify the remote scanner to function similarly and reuse the scan logic so that we always have the same results for a given package whether we use local or remote scanning.

Local Scan:

- unpack the `images/index.json` file to get a list of available images. Example:
```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 3237,
      "digest": "sha256:e7898cd05251d2af51380cbf50c9613748440fe6406e28e027846875b941c2de",
      "annotations": {
        "org.opencontainers.image.base.name": "quay.io/argoproj/argocd:v2.9.6"
      }
    }
  ]
}
```
- ignore any `annotations[org.opencontainers.image.base.name]` with *.att and *.sig 
- for all other images in the index:
  - read the json file in `images/blobs/sha256/<digest>`. This will give a list of layers. Example:

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "digest": "sha256:26997ab04178102d8549deff0abfcfb9455bd6a6e6f6a6723d3493d53d5a9097",
    "size": 7053
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:3153aa388d026c26a2235e1ed0163e350e451f41a8a313e1804d7e1afb857ab4",
      "size": 29533422
    }
...
  ]
}
```
  - extract the layers in the order they exist in the `layers` key into a temp directory
  - run `trivy rootfs` scan against the created directory

```[tasklist]
### Tasks
- [ ] local scans unpack the zarf package and scan using rootfs
- [ ] (optional) create a flag and leave the sbom scanner present so we can compare them
- [ ] local scans should report the architecture (can use zarf.yaml from archive)
```
