### ISSUE TITLE
CSV Write is outputting the header multiple times 

### ISSUE THREAD

**Issue by partkyle** [defenseunicorns/uds-security-hub#221]
This is a regression because we fixed this once. It was reintroduced when adding the JSON formatter. It's a easy fix, but we need to include some testing to make sure this doesn't happen again. It's an indicator that we don't have good testing on the output of the scan results.

```[tasklist]
### Tasks
- [ ] Create tests to validate the output of a test result for any output format supported
- [ ] tests need to validate the case of multiple output results and how they look in each format
- [ ] fix the multiple headers in csv format
```
