### ISSUE TITLE
Build Wolfi Package and Apko Image for uds-security-hub

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-security-hub#35]
## Description
We need to add support for building a Wolfi package and an Apko image This will enable us to distribute the application in a lightweight, secure, and reproducible manner.

## Tasks
- [ ] Create `melange.yaml` to define the Wolfi package
- [ ] Create `apko.yaml` to define the Apko image
- [ ] Update CI/CD pipeline to build and publish the Wolfi package and Apko image
- [ ] Test the Apko image to ensure `uds-security-hub` starts correctly

## Expected Result
- A Wolfi package and an Apko image for `uds-security-hub`
- Updated CI/CD pipeline for automated builds and publishing

## Relevant Files
- [melange.yaml](https://github.com/defenseunicorns/uds-security-hub/blob/naveen/feat/wolfi/melange.yaml) 
- [apko.yaml](https://github.com/defenseunicorns/uds-security-hub/blob/naveen/feat/wolfi/apko.yaml)
- CI/CD pipeline configuration (to be updated)

A WIP Progress branch https://github.com/defenseunicorns/uds-security-hub/tree/naveen/feat/wolfi
