### ISSUE TITLE
:book: Contributing.md

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-security-hub#80]
```[tasklist]
### Tasks
- [ ] Include docs for tools
- [ ] Include docs linter
- [ ] Include docs for `e2e`
```
